export let iso639 = [
    {code: 'ab', lang: 'Abkhaz'},
    {code: 'aa', lang: 'Afar'},
    {code: 'af', lang: 'Afrikaans'},
    {code: 'ak', lang: 'Akan'},
    {code: 'sq', lang: 'Albanian'},
    {code: 'am', lang: 'Amharic'},
    {code: 'ar', lang: 'Arabic'},
    {code: 'an', lang: 'Aragonese'},
    {code: 'hy', lang: 'Armenian'},
    {code: 'as', lang: 'Assamese'},
    {code: 'av', lang: 'Avaric'},
    {code: 'ae', lang: 'Avestan'},
    {code: 'ay', lang: 'Aymara'},
    {code: 'az', lang: 'Azerbaijani'},
    {code: 'bm', lang: 'Bambara'},
    {code: 'ba', lang: 'Bashkir'},
    {code: 'eu', lang: 'Basque'},
    {code: 'be', lang: 'Belarusian'},
    {code: 'bn', lang: 'Bengali; Bangla'},
    {code: 'bh', lang: 'Bihari'},
    {code: 'bi', lang: 'Bislama'},
    {code: 'bs', lang: 'Bosnian'},
    {code: 'br', lang: 'Breton'},
    {code: 'bg', lang: 'Bulgarian'},
    {code: 'my', lang: 'Burmese'},
    {code: 'ca', lang: 'Catalan; Valencian'},
    {code: 'ch', lang: 'Chamorro'},
    {code: 'ce', lang: 'Chechen'},
    {code: 'ny', lang: 'Chichewa; Chewa; Nyanja'},
    {code: 'zh', lang: 'Chinese'},
    {code: 'cv', lang: 'Chuvash'},
    {code: 'kw', lang: 'Cornish'},
    {code: 'co', lang: 'Corsican'},
    {code: 'cr', lang: 'Cree'},
    {code: 'hr', lang: 'Croatian'},
    {code: 'cs', lang: 'Czech'},
    {code: 'da', lang: 'Danish'},
    {code: 'dv', lang: 'Divehi; Dhivehi; Maldivian;'},
    {code: 'nl', lang: 'Dutch'},
    {code: 'dz', lang: 'Dzongkha'},
    {code: 'en', lang: 'English'},
    {code: 'eo', lang: 'Esperanto'},
    {code: 'et', lang: 'Estonian'},
    {code: 'ee', lang: 'Ewe'},
    {code: 'fo', lang: 'Faroese'},
    {code: 'fj', lang: 'Fijian'},
    {code: 'fi', lang: 'Finnish'},
    {code: 'fr', lang: 'French'},
    {code: 'ff', lang: 'Fula; Fulah; Pulaar; Pular'},
    {code: 'gl', lang: 'Galician'},
    {code: 'ka', lang: 'Georgian'},
    {code: 'de', lang: 'German'},
    {code: 'el', lang: 'Greek, Modern'},
    {code: 'gn', lang: 'Guaraní'},
    {code: 'gu', lang: 'Gujarati'},
    {code: 'ht', lang: 'Haitian; Haitian Creole'},
    {code: 'ha', lang: 'Hausa'},
    {code: 'he', lang: 'Hebrew (modern)'},
    {code: 'hz', lang: 'Herero'},
    {code: 'hi', lang: 'Hindi'},
    {code: 'ho', lang: 'Hiri Motu'},
    {code: 'hu', lang: 'Hungarian'},
    {code: 'ia', lang: 'Interlingua'},
    {code: 'id', lang: 'Indonesian'},
    {code: 'ie', lang: 'Interlingue'},
    {code: 'ga', lang: 'Irish'},
    {code: 'ig', lang: 'Igbo'},
    {code: 'ik', lang: 'Inupiaq'},
    {code: 'io', lang: 'Ido'},
    {code: 'is', lang: 'Icelandic'},
    {code: 'it', lang: 'Italian'},
    {code: 'iu', lang: 'Inuktitut'},
    {code: 'ja', lang: 'Japanese'},
    {code: 'jv', lang: 'Javanese'},
    {code: 'kl', lang: 'Kalaallisut, Greenlandic'},
    {code: 'kn', lang: 'Kannada'},
    {code: 'kr', lang: 'Kanuri'},
    {code: 'ks', lang: 'Kashmiri'},
    {code: 'kk', lang: 'Kazakh'},
    {code: 'km', lang: 'Khmer'},
    {code: 'ki', lang: 'Kikuyu, Gikuyu'},
    {code: 'rw', lang: 'Kinyarwanda'},
    {code: 'ky', lang: 'Kyrgyz'},
    {code: 'kv', lang: 'Komi'},
    {code: 'kg', lang: 'Kongo'},
    {code: 'ko', lang: 'Korean'},
    {code: 'ku', lang: 'Kurdish'},
    {code: 'kj', lang: 'Kwanyama, Kuanyama'},
    {code: 'la', lang: 'Latin'},
    {code: 'lb', lang: 'Luxembourgish, Letzeburgesch'},
    {code: 'lg', lang: 'Ganda'},
    {code: 'li', lang: 'Limburgish, Limburgan, Limburger'},
    {code: 'ln', lang: 'Lingala'},
    {code: 'lo', lang: 'Lao'},
    {code: 'lt', lang: 'Lithuanian'},
    {code: 'lu', lang: 'Luba-Katanga'},
    {code: 'lv', lang: 'Latvian'},
    {code: 'gv', lang: 'Manx'},
    {code: 'mk', lang: 'Macedonian'},
    {code: 'mg', lang: 'Malagasy'},
    {code: 'ms', lang: 'Malay'},
    {code: 'ml', lang: 'Malayalam'},
    {code: 'mt', lang: 'Maltese'},
    {code: 'mi', lang: 'M?ori'},
    {code: 'mr', lang: 'Marathi (Mar??h?)'},
    {code: 'mh', lang: 'Marshallese'},
    {code: 'mn', lang: 'Mongolian'},
    {code: 'na', lang: 'Nauru'},
    {code: 'nv', lang: 'Navajo, Navaho'},
    {code: 'nb', lang: 'Norwegian Bokmål'},
    {code: 'nd', lang: 'North Ndebele'},
    {code: 'ne', lang: 'Nepali'},
    {code: 'ng', lang: 'Ndonga'},
    {code: 'nn', lang: 'Norwegian Nynorsk'},
    {code: 'no', lang: 'Norwegian'},
    {code: 'ii', lang: 'Nuosu'},
    {code: 'nr', lang: 'South Ndebele'},
    {code: 'oc', lang: 'Occitan'},
    {code: 'oj', lang: 'Ojibwe, Ojibwa'},
    {code: 'cu', lang: 'Old Church Slavonic, Church Slavonic, Old Bulgarian'},
    {code: 'om', lang: 'Oromo'},
    {code: 'or', lang: 'Oriya'},
    {code: 'os', lang: 'Ossetian, Ossetic'},
    {code: 'pa', lang: 'Panjabi, Punjabi'},
    {code: 'pi', lang: 'P?li'},
    {code: 'fa', lang: 'Persian (Farsi)'},
    {code: 'pl', lang: 'Polish'},
    {code: 'ps', lang: 'Pashto, Pushto'},
    {code: 'pt', lang: 'Portuguese'},
    {code: 'qu', lang: 'Quechua'},
    {code: 'rm', lang: 'Romansh'},
    {code: 'rn', lang: 'Kirundi'},
    {code: 'ro', lang: 'Romanian'},
    {code: 'ru', lang: 'Russian'},
    {code: 'sa', lang: 'Sanskrit (Sa?sk?ta)'},
    {code: 'sc', lang: 'Sardinian'},
    {code: 'sd', lang: 'Sindhi'},
    {code: 'se', lang: 'Northern Sami'},
    {code: 'sm', lang: 'Samoan'},
    {code: 'sg', lang: 'Sango'},
    {code: 'sr', lang: 'Serbian'},
    {code: 'gd', lang: 'Scottish Gaelic; Gaelic'},
    {code: 'sn', lang: 'Shona'},
    {code: 'si', lang: 'Sinhala, Sinhalese'},
    {code: 'sk', lang: 'Slovak'},
    {code: 'sl', lang: 'Slovene'},
    {code: 'so', lang: 'Somali'},
    {code: 'st', lang: 'Southern Sotho'},
    {code: 'az', lang: 'South Azerbaijani'},
    {code: 'es', lang: 'Spanish; Castilian'},
    {code: 'su', lang: 'Sundanese'},
    {code: 'sw', lang: 'Swahili'},
    {code: 'ss', lang: 'Swati'},
    {code: 'sv', lang: 'Swedish'},
    {code: 'ta', lang: 'Tamil'},
    {code: 'te', lang: 'Telugu'},
    {code: 'tg', lang: 'Tajik'},
    {code: 'th', lang: 'Thai'},
    {code: 'ti', lang: 'Tigrinya'},
    {code: 'bo', lang: 'Tibetan Standard, Tibetan, Central'},
    {code: 'tk', lang: 'Turkmen'},
    {code: 'tl', lang: 'Tagalog'},
    {code: 'tn', lang: 'Tswana'},
    {code: 'to', lang: 'Tonga (Tonga Islands)'},
    {code: 'tr', lang: 'Turkish'},
    {code: 'ts', lang: 'Tsonga'},
    {code: 'tt', lang: 'Tatar'},
    {code: 'tw', lang: 'Twi'},
    {code: 'ty', lang: 'Tahitian'},
    {code: 'ug', lang: 'Uyghur, Uighur'},
    {code: 'uk', lang: 'Ukrainian'},
    {code: 'ur', lang: 'Urdu'},
    {code: 'uz', lang: 'Uzbek'},
    {code: 've', lang: 'Venda'},
    {code: 'vi', lang: 'Vietnamese'},
    {code: 'vo', lang: 'Volapük'},
    {code: 'wa', lang: 'Walloon'},
    {code: 'cy', lang: 'Welsh'},
    {code: 'wo', lang: 'Wolof'},
    {code: 'fy', lang: 'Western Frisian'},
    {code: 'xh', lang: 'Xhosa'},
    {code: 'yi', lang: 'Yiddish'},
    {code: 'yo', lang: 'Yoruba'},
    {code: 'za', lang: 'Zhuang, Chuang'},
    {code: 'zu', lang: 'Zulu'}];
